import ROOT

# Open the file
f = ROOT.TFile("ex9.root")

# Get the tree
tree = f.Get("tree")

# Create a canvas
canvas = ROOT.TCanvas("canvas", "", 800, 600)
canvas.Divide(2, 1)

# Create a histogram
pt = ROOT.TH1F("pt", "Pt generated by PYTHIA8", 500, 0, 10)
eta = ROOT.TH1F("eta", "Eta generated by PYTHIA8", 100, -10, 10)

# Loop over the events
for event in tree:
    pt.Fill(event.Pt)
    eta.Fill(event.Eta)

# Customize the histogram properties
pt.SetLineColor(ROOT.kBlack)
pt.SetLineWidth(2)
pt.SetStats(0)

eta.SetLineColor(ROOT.kBlack)
eta.SetLineWidth(2)
eta.SetStats(0)

# Customize the canvas properties
canvas.SetFillColor(ROOT.kWhite)
canvas.SetLeftMargin(0.15)
canvas.SetBottomMargin(0.15)

# Add axis labels
pt.GetXaxis().SetTitle("P_{T}")
pt.GetYaxis().SetTitle("Events")

eta.GetXaxis().SetTitle("#eta")
eta.GetYaxis().SetTitle("Events")

# Draw the histogram
canvas.cd(1)
pt.Draw()

canvas.cd(2)
eta.Draw()

# Save the canvas
canvas.SaveAs("plots.root")
canvas.SaveAs("plots.pdf")
canvas.SaveAs("plots.png")

# Close the file
f.Close()
